[package]
name = "Calendar"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
incremental = true
split-debuginfo = "packed"
strip = "symbols"

[profile.dev]
opt-level = 0
