name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    name: ${{ matrix.platform.os_name }} with Rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: calendar-linux-arm64
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: calendar-linux-x86_64
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: calendar-windows-x86_64.exe
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: calendar-darwin-x86_64
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: calendar-darwin-arm64
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true

      - name: Rename binary (linux and macos)
        if: matrix.platform.os_name != 'Windows-x86_64'
        run: mv target/${{ matrix.platform.target }}/release/calendar target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

      - name: Generate ZIP (Windows)
        if: matrix.platform.os_name == 'Windows-x86_64'
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar.exe -a -c -f calendar-windows-x86_64.zip calendar.exe

      - name: Rename binary (windows)
        run: mv target/${{ matrix.platform.target }}/release/calendar.exe target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
        if: matrix.platform.os_name == 'Windows-x86_64'

      - name: Generate Debian package
        run: cargo install cargo-deb && cargo deb --output target/debian/calendar-debian.deb
        if: matrix.platform.os_name == 'Linux-x86_64'

      - name: Release binary
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

      - name: Release Debian package
        uses: softprops/action-gh-release@v1
        if: matrix.platform.os_name == 'Linux-x86_64'
        with:
          files: |
            target/debian/calendar-debian.deb

      - name: Release Windows zip
        uses: softprops/action-gh-release@v1
        if: matrix.platform.os_name == 'Windows-x86_64'
        with:
          files: |
            target/${{ matrix.platform.target }}/release/calendar-windows-x86_64.zip\
